Biblioteca/Controllers/RolesController.cs
using Biblioteca.Models.Domain;
using Biblioteca.Models.Servicios.IServices;
using Biblioteca.Models.Servicios.Services;
using Microsoft.AspNetCore.Mvc;

namespace Biblioteca.Controllers
{
    public class RolesController : Controller
    {
        private readonly IRolServices _rolServices;

        public RolesController(IRolServices rolServices)
        {
            _rolServices = rolServices;
        }
        public IActionResult IndexRol()
        {
            var results = _rolServices.GetRol();
            return View(results);
        }

        [HttpGet]
        public IActionResult Crear()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(Rol req)
        {
            var result = _rolServices.Create(req);
            return RedirectToAction(nameof(IndexRol));
        }

        //Editar Agusto
        [HttpGet]
        public IActionResult Editar(int id)
        {
            var rol = _rolServices.GetRolById(id);

            return View(rol);
        }

        [HttpPost]
        public IActionResult Editar(Rol rol)
        {
            try
            {
                if (rol == null)
                {
                    ModelState.AddModelError("", "Datos invalidos");
                    return View(rol);
                }

                var editado = _rolServices.Editar(rol);

                if (editado != null)
                {
                    return RedirectToAction("IndexRol");
                }

                ModelState.AddModelError("", "Errol al Editar el Rol");
                return View(rol);

            } catch (Exception ex)
            {
                ModelState.AddModelError("", "Error al editar: " + ex.Message);
                return View(rol);
            }
        }

        //Eliminar
        [HttpPost]
        public IActionResult Eliminar(int id)
        {
            var result = _rolServices.EliminarRol(id);

            if (result)
            {
                TempData["SuccessMessage"] = "Rol Eliminado Correctamente";
            } else
            {
                TempData["ErrorMessage"] = "No se Pudo Eliminar el Rol";
            }

            return RedirectToAction("IndexRol");
        }
    }
}

Biblioteca/Controllers/UsuarioController.cs
using Biblioteca.Context;
using Biblioteca.Models.Domain;
using Biblioteca.Models.Servicios.IServices;
using Biblioteca.Models.Servicios.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace Biblioteca.Controllers
{
    public class UsuarioController : Controller
    {
        private readonly IUsuarioServices _usuaarioServices;
        private readonly IRolServices _rolServices;

        public UsuarioController(IUsuarioServices usuaarioServices, IRolServices rolServices)
        {
            _usuaarioServices = usuaarioServices;
            _rolServices = rolServices;
        } 
        public IActionResult Index()
        {
            var result = _usuaarioServices.GetUsuarios();

            return View(result);
        }

        [HttpGet]
        public async Task<IActionResult> Crear()
        {
            List<Rol> result = await _rolServices.GetAllRol();
            ViewBag.Roles = result.Select(p => new SelectListItem()
            {
                Text = p.Nombre,
                Value = p.PkRol.ToString()
            });

            return View();
        }

        [HttpPost]
        public IActionResult Create(Usuario req)
        {
            var result = _usuaarioServices.Create(req);
            return RedirectToAction(nameof(Index));
        }

        [HttpGet]
        public async Task<IActionResult> Editar(int id)
        {
            List<Rol> Rol = await _rolServices.GetAllRol();
            ViewBag.Roles = Rol.Select(p => new SelectListItem()
            {
                Text = p.Nombre,
                Value = p.PkRol.ToString()
            });

            var result = _usuaarioServices.GetbyId(id);

            return View(result);
        }

        [HttpPost]
        public IActionResult Editar(Usuario usuario)
        {
            try
            {
                if (usuario == null)
                {
                    ModelState.AddModelError("", "Datos inválidos.");
                    return View(usuario);
                }

                var editado = _usuaarioServices.Editar(usuario);

                if (editado != null)
                {
                    return RedirectToAction("Index");
                }

                ModelState.AddModelError("", "Error al editar el usuario.");
                return View(usuario);
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", "Error al editar: " + ex.Message);
                return View(usuario);
            }
        }

        [HttpPost]
        public IActionResult Eliminar(int id)
        {
            var result = _usuaarioServices.EliminarUsuario(id);

            if (result)
            {
                TempData["SuccessMessage"] = "Usuario Eliminado Correctamenete";
            }
            else
            {
                TempData["ErrorMessage"] = "No se Pudo Eliminar el Usuario";
            }

            return RedirectToAction("Index");
        }
    }
}

Biblioteca/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Biblioteca</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Biblioteca.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Biblioteca</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2025 - Biblioteca - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Biblioteca/Views/Shared/_LayoutDashboard.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Biblioteca</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Biblioteca.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
            <div class="container-fluid">
                <button class="btn active text-white" type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvasExample" aria-controls="offcanvasExample">
                    Menú
                </button>

                <!-- Nombre o logo -->
                <a class="navbar-brand ms-3" href="#">Dashboard</a>

                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarNav">
                    <ul class="navbar-nav ms-auto">
                        <form class="d-flex" role="search">
                            <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
                            <button class="btn btn-outline-success" type="submit">Search</button>
                        </form>
                    </ul>
                </div>
            </div>
        </nav>
    </header>

    <main>
        <div class="offcanvas offcanvas-start bg-white text-white" tabindex="-1" id="offcanvasExample" aria-labelledby="offcanvasExampleLabel">
            <div class="offcanvas-header">
                <h5 class="offcanvas-title text-black" id="offcanvasExampleLabel">Usuario</h5>
                <button type="button" class="btn-close" data-bs-dismiss="offcanvas" aria-label="Close"></button>
            </div>
            <div class="offcanvas-body">
                <div class="d-flex flex-column align-items-center">
                    <img src="~/images/user.png" class="img-fluid rounded-circle mb-3" alt="Imagen de usuario" style="width: 150px; height: 150px;" />
                    <ul class="nav flex-column">
                        <li class="nav-item">
                            <a class="nav-link active text-black text-lg-center fs-4" aria-current="page" asp-controller="Usuario" asp-action="Index">Dashboard</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-black text-lg-center fs-4" aria-current="page" asp-controller="Roles" asp-action="IndexRol">Roles</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-black text-lg-center fs-4" href="#">Configuración</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-black text-lg-center fs-4" href="#">Cerrar sesión</a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
        @RenderBody()
        @RenderSection("scripts", required: false)
    </main>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>